#!/bin/bash
# Copyright (C) 2022, Raffaello Bonghi <raffaello@rnext.it>
# All rights reserved
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 1. Redistributions of source code must retain the above copyright 
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of the copyright holder nor the names of its 
#    contributors may be used to endorse or promote products derived 
#    from this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND 
# CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, 
# BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; 
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE 
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, 
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

NANOSAUR_DATA='/opt/nanosaur'

# Variable stored in configuration file
ROS2_PATH='/opt/ros/foxy/setup.bash'
ROS_DEV_WS_NAME='ros_ws'
ROS_CORE_WS_NAME='nanosaur_ws'
ROS_PERC_WS_NAME='nanosaur_perception'
DOCKER_TAG='latest'
BRANCH_TAG='master'
DOCKER_NETWORK='host'
# Load nanosaur configuration file
if [ -f $NANOSAUR_DATA/.env ] ; then
    source $NANOSAUR_DATA/.env
fi

# Default variable
NANOSAUR_L4T="32.6.1"
NANOSAUR_VERSION='2.0.0'
ROBOT_NAME='nanosaur'
ROBOT_FILE_PATH=$NANOSAUR_DATA/'param/robot.yml'
NANOSAUR_DEV_WS_PATH=$HOME/$ROS_DEV_WS_NAME
NANOSAUR_CORE_WS_PATH=$HOME/$ROS_CORE_WS_NAME
NANOSAUR_PERCEPTION_WS_PATH=$HOME/$ROS_PERC_WS_NAME
ISAAC_ROS_WS_PATH=$HOME/isaac_ros_ws

############################################################################################

bold=`tput bold`
red=`tput setaf 1`
green=`tput setaf 2`
yellow=`tput setaf 3`
blue=`tput setaf 4`
reset=`tput sgr0`

# Load platform
# - aarch64 = NVIDIA Jetson
# - x86_64 = Desktop
PLATFORM="desktop"
#CHECK_JETSON=$(dpkg-query --showformat='${Version}' --show nvidia-l4t-core)
#echo $CHECK_JETSON
if [[ "$(uname -m)" = "aarch64" ]] ; then
    PLATFORM="robot"
fi
# PLATFORM="$(uname -m)"

# Modules check sudo
# https://serverfault.com/questions/266039/temporarily-increasing-sudos-timeout-for-the-duration-of-an-install-script
sudo_me()
{
    local start=$1
    # write sudo me file
    local sudo_stat="/tmp/nanosaur_sudo_status"
    # No sudo loop
    if $start ; then
        touch $sudo_stat
        # Loop script
        while [ -f $sudo_stat ]; do
            # echo "checking $$ ...$(date)"
            sudo -v
            sleep 5
        done &
    else
        if [ -f $sudo_stat ] ; then
            rm $sudo_stat
        fi
    fi
}

get_nanosaur_rosinstall()
{
    local branch=$BRANCH_TAG
    # Load rosinstall configuration
    local ROSINSTALL_FILE="https://raw.githubusercontent.com/rnanosaur/nanosaur/$branch/nanosaur/rosinstall/desktop.rosinstall"
    if [[ $PLATFORM = "robot" ]] ; then
        ROSINSTALL_FILE="https://raw.githubusercontent.com/rnanosaur/nanosaur/$branch/nanosaur/rosinstall/robot.rosinstall"
    fi
    echo $ROSINSTALL_FILE
}

get_perception_rosinstall()
{
    local branch=$BRANCH_TAG
    # Load rosinstall configuration
    echo "https://raw.githubusercontent.com/rnanosaur/nanosaur_perception/$branch/nanosaur_perception/rosinstall/perception.rosinstall"
}

############################ CONFIG functions #################################################

config_info()
{
    echo " - ${bold}Branch:${reset} ${green}$BRANCH_TAG${reset}" >&2
    if [[ $PLATFORM = "robot" ]] ; then
        echo " - ${bold}Network:${reset} ${green}$DOCKER_NETWORK${reset}" >&2
        echo " - ${bold}Tag:${reset} ${green}$DOCKER_TAG${reset}" >&2
    fi
    if [ ! -z ${ROS_DOMAIN_ID+x} ] ; then
        echo " - ${bold}ROS_DOMAIN_ID:${reset} ${green}$ROS_DOMAIN_ID${reset}" >&2
    else
        echo " - ${bold}ROS_DOMAIN_ID:${reset} 0 ${yellow}(not set)${reset}" >&2
    fi
}

config_save()
{
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#variable-substitution
    echo "BRANCH_TAG=$BRANCH_TAG" > $NANOSAUR_DATA/.env
    if [[ $PLATFORM = "robot" ]] ; then
        echo "DOCKER_NETWORK=$DOCKER_NETWORK" >> $NANOSAUR_DATA/.env
        echo "DOCKER_TAG=$DOCKER_TAG" >> $NANOSAUR_DATA/.env
    fi
    if [ ! -z ${ROS_DOMAIN_ID+x} ] ; then
        echo "ROS_DOMAIN_ID=$ROS_DOMAIN_ID" >> $NANOSAUR_DATA/.env
    fi
}

############################ BRANCH/DISTRO functions ###########################################

set_branch()
{
    local arguments=$1
    if [ ! -z "$arguments" ] ; then
        # Set BRANCH_TAG and save
        BRANCH_TAG=$arguments
        config_save
    fi
    echo "${bold}Branch:${reset} ${green}$BRANCH_TAG${reset}" >&2
}

set_distro()
{
    local arguments=$1
    # Update branch
    if [ ! -z "$arguments" ] ; then
        # Set BRANCH_TAG and save
        BRANCH_TAG=$arguments
        # Update docker tag distro
        echo "TODO add docker tag distro"
        DOCKER_TAG=$arguments
        config_save
    fi
    echo "${bold}Distro:${reset} ${green}$DOCKER_TAG${reset}" >&2
}

set_domain()
{
    local arguments=$1
    # https://docs.ros.org/en/ros2_documentation/foxy/Concepts/About-Domain-ID.html
    if [ ! -z "$arguments" ] ; then
        # Check if is a number
        local re='^[0-9]+$'
        if ! [[ $arguments =~ $re ]] ; then
            echo "${red}error: Not a number${reset}" >&2
            exit 1
        fi
        # Set ROS_DOMAIN_ID
        ROS_DOMAIN_ID=$arguments
        config_save
    fi
    # Read ROS_DOMAIN_ID variable
    local domain=0
    if [ -z ${ROS_DOMAIN_ID+x} ] ; then
        echo "${yellow}Unset variable${reset}"
    else
        domain=$ROS_DOMAIN_ID
    fi
    echo "ROS_DOMAIN_ID=$domain"
}

############################ BUILD functions ##################################################

build_usage()
{
    if [ "$1" != "" ]; then
        echo "${red}$1${reset}" >&2
    fi

    echo "This script build all workspaces." >&2
    echo "nanosaur build [options]" >&2
    echo "${bold}options:${reset}" >&2
    echo "   -h|--help            | This help" >&2
}

build()
{
    while [ -n "$1" ]; do
        case "$1" in
            -h|--help) # Load help
                build_usage
                exit 0
                ;;
            *)
                build_usage "[ERROR] Unknown option: $1" >&2
                exit 1
                ;;
        esac
            shift 1
    done

    # Run update function
    local THIS="$(pwd)"
    # Load ROS2 workspace
    source $ROS2_PATH
    # Go to catkin path
    cd $NANOSAUR_CORE_WS_PATH
    # Catkin make all workspace
    echo " ${bold}*${reset} ${green}colcon build${reset} $(basename $NANOSAUR_CORE_WS_PATH)" >&2
    colcon build --symlink-install 
    # Return to main path
    cd $THIS
}

############################ UPDATE functions #################################################

update_usage()
{
    if [ "$1" != "" ]; then
        echo "${red}$1${reset}" >&2
    fi

    echo "This script update your robot or your desktop." >&2
    echo "nanosaur update [options]" >&2
    echo "${bold}options:${reset}" >&2
    if [[ $PLATFORM = "desktop" ]] ; then
        echo "   rosinstall           | Download all rosinstall dependecies" >&2
    else
        echo "   --clean              | Clean docker after update" >&2
    fi
    echo "   -h|--help            | This help" >&2
}

update_nanosaur_tools()
{
    local branch=$BRANCH_TAG
    # Update nanosaur script and bash completition script
    if [ ! -d $NANOSAUR_CORE_WS_PATH ] ; then
        echo " - ${bold}${green}Pull nanosaur command${reset} and copy in $NANOSAUR_DATA" >&2
        curl https://raw.githubusercontent.com/rnanosaur/nanosaur/$branch/nanosaur/scripts/nanosaur -o $NANOSAUR_DATA/nanosaur
        chmod +x $NANOSAUR_DATA/nanosaur

        echo " - ${bold}${green}Pull nanosaur bash completition${reset} in $NANOSAUR_DATA" >&2
        curl -sSL https://raw.githubusercontent.com/rnanosaur/nanosaur/$branch/nanosaur/scripts/completition.bash  -o $NANOSAUR_DATA/completition.bash
    fi
}

update_developer()
{
    # Update core rosinstall packages
    if [ -d $NANOSAUR_CORE_WS_PATH/src ] ; then
        # Import workspace
        if [ -d $NANOSAUR_CORE_WS_PATH/src/nanosaur/nanosaur/rosinstall ] ; then
            echo " - ${green}Check status all workspaces${reset} Branch: ${bold}$BRANCH_TAG${reset}" >&2
            local rosinstall_name="desktop.rosinstall"
            if [[ $PLATFORM = "aarch64" ]] ; then
                rosinstall_name="robot.rosinstall"
            fi
            vcs import $NANOSAUR_CORE_WS_PATH/src < $NANOSAUR_CORE_WS_PATH/src/nanosaur/nanosaur/rosinstall/$rosinstall_name
            vcs pull $NANOSAUR_CORE_WS_PATH/src
        else
            echo " - ${bold}${green}Download and update Nanosaur rosinstall${reset}" >&2
            curl $(get_nanosaur_rosinstall) -o $NANOSAUR_DATA/nanosaur.rosinstall
            vcs import $NANOSAUR_CORE_WS_PATH/src < $NANOSAUR_DATA/nanosaur.rosinstall
            rm $NANOSAUR_DATA/nanosaur.rosinstall
        fi
        # Status update
        if [ $? -ne 0 ] ; then
            # Try to make again
            echo "${red}Please check workspace status ${reset}" >&2
            # sudo_me false
            exit 1
        fi
    fi

    # Update package perception on robot
    if [[ $PLATFORM = "robot" ]] ; then
        if [ -d $NANOSAUR_PERCEPTION_WS_PATH/src ] ; then
            # Import workspace
            if [ -d $NANOSAUR_PERCEPTION_WS_PATH/src/nanosaur_perception/nanosaur_perception/rosinstall ] ; then
                echo " - ${green}Check status all perception workspaces${reset} Branch: ${bold}$BRANCH_TAG${reset}" >&2
                local path_perception=$NANOSAUR_PERCEPTION_WS_PATH/src/nanosaur_perception/nanosaur_perception/rosinstall/perception.rosinstall
                vcs import $NANOSAUR_PERCEPTION_WS_PATH/src < $path_perception
                vcs pull $NANOSAUR_PERCEPTION_WS_PATH/src
            else
                echo " - ${bold}${green}Download and update perception rosinstall${reset}" >&2
                curl $(get_perception_rosinstall) -o $NANOSAUR_DATA/perception.rosinstall
                vcs import $NANOSAUR_PERCEPTION_WS_PATH/src < $NANOSAUR_DATA/perception.rosinstall
                rm $NANOSAUR_DATA/perception.rosinstall
            fi
            # Status update
            if [ $? -ne 0 ] ; then
                # Try to make again
                echo "${red}Please check workspace status ${reset}" >&2
                # sudo_me false
                exit 1
            fi
        fi
    fi
}

update_on_robot()
{
    local CLEAN=$1
    # Switch off nanosaur
    docker-compose -f $NANOSAUR_DATA/docker-compose.yml down
    # Update docker-compose
    if [ -d $NANOSAUR_CORE_WS_PATH ] ; then
        if [ ! -L $NANOSAUR_DATA/docker-compose.yml ] ; then
            echo " - ${bold}${green}Link Nanosaur docker-compose${reset}" >&2
            ln -s  $NANOSAUR_CORE_WS_PATH/src/nanosaur/docker-compose.yml $NANOSAUR_DATA/docker-compose.yml
        fi
    else
        # Download latest version nanosaur docker-compose
        echo " - ${bold}${green}Download Nanosaur docker-compose${reset}" >&2
        # Download the docker-compose image and run
        local branch=$BRANCH_TAG
        curl https://raw.githubusercontent.com/rnanosaur/nanosaur/$branch/docker-compose.yml -o $NANOSAUR_DATA/docker-compose.yml
    fi
    echo " - ${bold}${green}Pull and restart all containers DISTRO: $DOCKER_TAG${reset}" >&2
    # Pull all new images
    docker-compose -f $NANOSAUR_DATA/docker-compose.yml pull
    # Clean images after pull
    if $CLEAN ; then
        docker image prune -f
    fi
}

update()
{
    local rosinstall=false
    local CLEAN=false
	# Decode all information from startup
    while [ -n "$1" ]; do
        case "$1" in
            -h|--help) # Load help
                update_usage
                exit 0
                ;;
            rosinstall)
                if [[ $PLATFORM = "desktop" ]] ; then
                    rosinstall=true
                fi
                ;;
            --clean)
                CLEAN=true
                ;;
            *)
                update_usage "[ERROR] Unknown option: $1" >&2
                exit 1
                ;;
        esac
            shift 1
    done

    if $rosinstall ; then
        # Request sudo password
        sudo -v
        sudo_me true
    fi

    # Update all nanosaur tools
    update_nanosaur_tools
    # Update developer packages
    update_developer

    if $rosinstall ; then
        # Load ROS2 workspace
        source $ROS2_PATH
        echo " - ${bold}${green}Update rosdep${reset}" >&2
        # Update rosdep
        rosdep update
        # Install all dependencies
        # http://wiki.ros.org/rosdep
        echo " ${bold}*${reset} Install all ${bold}dependencies${reset}" >&2
        rosdep install --from-paths $NANOSAUR_CORE_WS_PATH/src --ignore-src -r -y

        # Disable sudo me
        sudo_me false
    fi

    # Install Docker and other scripts
    if [[ $PLATFORM = "robot" ]] ; then
        update_on_robot $CLEAN
    fi
}

############################ INSTALL functions ################################################

installer_usage()
{
    if [ "$1" != "" ]; then
        echo "${red}$1${reset}" >&2
    fi

    echo "Use this option to install nansaur on your desktop or your NVIDIA Jetson" >&2
    echo "nanosaur install [options]" >&2
    echo "${bold}options:${reset}" >&2
    echo "   developer            | Install nanosaur in developer mode (install in ${bold}$NANOSAUR_CORE_WS_PATH${reset} workspace)" >&2
    echo "   -y                   | Run this script silent" >&2
    echo "   --force              | Force to install nanosaur anyway" >&2
    echo "   -h|--help            | This help" >&2
}

install_nanosaur_tools()
{
    # Check if exist the nanosaur workspace
    if [ -d $NANOSAUR_CORE_WS_PATH ] ; then
        if [ -f $NANOSAUR_DATA/nanosaur ] ; then
            rm $NANOSAUR_DATA/nanosaur 
        fi
        if [ ! -L $NANOSAUR_DATA/nanosaur ] ; then
            echo " - Link nanosaur command in ${bold}${green}$NANOSAUR_DATA${reset}"
            ln -s $NANOSAUR_CORE_WS_PATH/src/nanosaur/nanosaur/scripts/nanosaur $NANOSAUR_DATA/nanosaur
        fi
        if [ ! -L $NANOSAUR_DATA/completition.bash ] ; then
            echo " - Link nanosaur completition in ${bold}${green}$NANOSAUR_DATA${reset}"
            ln -s $NANOSAUR_CORE_WS_PATH/src/nanosaur/nanosaur/scripts/completition.bash $NANOSAUR_DATA/completition.bash
        fi
    else
        echo " - ${bold}${green}Move nanosaur command${reset} in $NANOSAUR_DATA"
        mv $HOME/nanosaur $NANOSAUR_DATA/nanosaur
        chmod +x $NANOSAUR_DATA/nanosaur

        echo " - ${bold}${green}Copy nanosaur bash completition${reset} in $NANOSAUR_DATA"
        curl -sSL https://raw.githubusercontent.com/rnanosaur/nanosaur/master/nanosaur/scripts/completition.bash  -o $NANOSAUR_DATA/completition.bash
    fi

    # link nanosaur script to nanosaur path
    if [ ! -L /usr/local/bin/nanosaur ] ; then
        echo " - Link nanosaur command in ${bold}${green}/usr/local/bin${reset}"
        sudo ln -s $NANOSAUR_DATA/nanosaur /usr/local/bin/nanosaur
    fi

    # link nanosaur bash completition
    if [ ! -L /etc/bash_completion.d/nanosaur ] ; then
        echo " - Link nanosaur bash completition in ${bold}${green}/etc/bash_completion.d/${reset}"
        sudo ln -s $NANOSAUR_DATA/completition.bash /etc/bash_completion.d/nanosaur
    fi
}

install_developer()
{
    if ! command -v vcs &> /dev/null ; then
        echo " - Install vcs tool"
        sudo apt update && sudo apt install curl gnupg2 lsb-release -y
        sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key  -o /usr/share/keyrings/ros-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
        sudo apt update && sudo apt-get install python3-vcstool -y
    fi

    # make folder for nanosaur core workspace
    if [ ! -d $NANOSAUR_CORE_WS_PATH ] ; then
        echo " - ${bold}${green}Make nanosaur workspace folder in $NANOSAUR_CORE_WS_PATH${reset}"
        mkdir -p $NANOSAUR_CORE_WS_PATH/src 
    fi

    # make folder for nanosaur perception workspace
    if [[ $PLATFORM = "robot" ]] ; then
        if [ ! -d $NANOSAUR_PERCEPTION_WS_PATH ] ; then
            echo " - ${bold}${green}Make nanosaur_perception workspace folder in $NANOSAUR_PERCEPTION_WS_PATH${reset}"
            mkdir -p $NANOSAUR_PERCEPTION_WS_PATH/src 
        fi
    fi
}

install_on_robot()
{
    if ! command -v pip3 &> /dev/null ; then
        echo " - ${bold}${green}Install pip/pip3${reset}"
        sudo apt-get install -y python3-pip
    fi

    # Check if is installed nano
    if ! command -v nano &> /dev/null ; then
        echo " - ${bold}${green}Install nano${reset}"
        sudo apt-get install -y nano
    fi

    # Check if is installed jtop
    if ! command -v jtop &> /dev/null ; then
        echo " - ${bold}${green}Install/Update jetson-stats${reset}"
        sudo -H pip3 install -U jetson-stats
    fi

    # Check if is installed ros2_system_manager
    if [ ! -f /usr/lib/ros2_system_manager/system_manager_server ] ; then
        echo " - ${bold}${green}Install/Update ros2_system_manager${reset}"
        sudo -H pip3 install -U ros2-system-manager
    fi

    if ! getent group docker | grep -q "\b$USER\b" ; then
        echo " - Add docker permissions to ${bold}${green}user=$USER${reset}"
        sudo usermod -aG docker $USER
    fi

    # Check if is installed docker-compose
    if ! command -v docker-compose &> /dev/null ; then
        echo " - ${bold}${green}Install docker-compose${reset}"
        sudo apt-get install -y libffi-dev python-openssl libssl-dev
        sudo -H pip3 install -U pip
        sudo pip3 install -U docker-compose
    fi

    local branch=$BRANCH_TAG

    if [ -d $NANOSAUR_CORE_WS_PATH ] ; then
        if [ ! -L $NANOSAUR_DATA/docker-compose.yml ] ; then
            echo " - ${bold}${green}Link Nanosaur docker-compose${reset}" >&2
            ln -s  $NANOSAUR_CORE_WS_PATH/src/nanosaur/docker-compose.yml $NANOSAUR_DATA/docker-compose.yml
        fi
    else
        # Download latest version nanosaur docker-compose
        echo " - ${bold}${green}Download Nanosaur docker-compose${reset}" >&2
        # Download the docker-compose image and run
        curl https://raw.githubusercontent.com/rnanosaur/nanosaur/$branch/docker-compose.yml -o $NANOSAUR_DATA/docker-compose.yml
    fi

    # Make sure the nvidia docker runtime will be used for builds
    local DEFAULT_RUNTIME=$(docker info | grep "Default Runtime: nvidia" ; true)
    if [[ -z "$DEFAULT_RUNTIME" ]]; then
        echo "${green} - Download docker daemon.json${reset}"
        curl https://raw.githubusercontent.com/rnanosaur/nanosaur/$branch/nanosaur/scripts/daemon.json -o $NANOSAUR_DATA/daemon.json
        echo "${green} - Set runtime nvidia on /etc/docker/daemon.json${reset}"
        sudo mv /etc/docker/daemon.json /etc/docker/daemon.json.bkp
        sudo cp $NANOSAUR_DATA/daemon.json /etc/docker/daemon.json
        echo "${green} - Restart docker service${reset}"
        sudo systemctl restart docker.service
    fi

    # Create nanosaur docker
    echo " - ${bold}${green}Start nanosaur docker-compose${reset}"
    sudo docker-compose -f $NANOSAUR_DATA/docker-compose.yml up -d
}

installer()
{
    local developer=false
    local SILENT=false
    local FORCE=true
	# Decode all information from startup
    while [ -n "$1" ]; do
        case "$1" in
            -h|--help) # Load help
                installer_usage
                exit 0
                ;;
            --force)
                FORCE=true
                ;;
            -y)
                SILENT=true
                ;;
            developer)
                developer=true
                ;;
            *)
                installer_usage "[ERROR] Unknown option: $1" >&2
                exit 1
                ;;
        esac
            shift 1
    done

    # Check if is installed on the same Jetpack
    if [[ $PLATFORM = "robot" ]] ; then
        # Read version
        local JETSON_L4T_STRING=$(dpkg-query --showformat='${Version}' --show nvidia-l4t-core)
        # extract version
        local JETSON_L4T_ARRAY=$(echo $JETSON_L4T_STRING | cut -f 1 -d '-')
        # Load release and revision
        local JETSON_L4T_RELEASE=$(echo $JETSON_L4T_ARRAY | cut -f 1 -d '.')
        local JETSON_L4T_REVISION=${JETSON_L4T_ARRAY#"$JETSON_L4T_RELEASE."}

        if [[ $JETSON_L4T_RELEASE.$JETSON_L4T_REVISION != $NANOSAUR_L4T ]] ; then
            echo "${bold}${red}You cannot install nanosaur on this Jetpack with L4T $JETSON_L4T_RELEASE.$JETSON_L4T_REVISION need L4T $NANOSAUR_L4T ${reset}"
            if ! $FORCE ; then
                exit 0
            fi
        fi
    fi

    local type_developer=""
    # Recap installatation
    echo "------ Configuration ------"
    if $developer ; then
        echo " - ${bold}Developer:${reset} ${yellow}$developer${reset}"
    fi
    echo " - ${bold}Install on:${reset} ${green}$PLATFORM${reset}"
    echo " - ${bold}User:${reset} ${green}$USER${reset} - ${bold}Hostname:${reset} ${green}$HOSTNAME${reset}"
    config_info
    echo "---------------------------"

    while ! $SILENT; do
        read -p "Do you wish to install nanosaur on this platform? [Y/n] " yn
            case $yn in
                [Yy]* ) # Break and install jetson_stats 
                        break;;
                [Nn]* ) exit;;
            * ) echo "Please answer yes or no.";;
        esac
    done

    # curl https://raw.githubusercontent.com/rnanosaur/nanosaur/master/nanosaur/scripts/nanosaur -o $HOME/nanosaur && \
    # chmod +x $HOME/nanosaur && nanosaur install

    # Request sudo password
    sudo -v

    if [ ! -d $NANOSAUR_DATA ] ; then
        echo " - ${bold}${green}Make nanosaur folder in $NANOSAUR_DATA${reset}"
        # Build nanosaur folder structure
        # - /opt/nanosaur
        # -      /param [ ros2 parameter folder ]
        sudo mkdir -p $NANOSAUR_DATA
        sudo chown $USER:$USER $NANOSAUR_DATA
        mkdir -p "$NANOSAUR_DATA/param"
    fi

    if $developer ; then
        # Make folders
        install_developer
    fi
    # Install nanosaur tools
    install_nanosaur_tools
    # Install Docker and other scripts
    if [[ $PLATFORM = "robot" ]] ; then
        install_on_robot
    else
        # Run ronsintall
        update rosinstall
        # Run builder
        build
    fi

    if [ -f /var/run/reboot-required ] ; then
        # After install require reboot
        echo "${red}*** System Restart Required ***${reset}"
    fi
}

############################ INFO functions ####################################################

info()
{
    local verbose=false
	# Decode all information from startup
    while [ -n "$1" ]; do
        case "$1" in
            -h|--help) # Load help
                info_usage
                exit 0
                ;;
            -v|--verbose)
                verbose=true
                ;;
            *)
                install_usage "[ERROR] Unknown option: $1" >&2
                exit 1
                ;;
        esac
            shift 1
    done

    # Status configurations
    local arch="$(uname -m)"
    echo "${bold}Configuration:${reset}" >&2
    echo " - ${bold}Architecture:${reset} ${green}$arch${reset} - ${bold}type:${reset} ${green}$PLATFORM${reset}" >&2
    echo " - ${bold}nanosaur folder:${reset} ${green}$NANOSAUR_DATA${reset}" >&2
    config_info
    if $verbose ; then
        # Status workspaces
        if [ -d $NANOSAUR_CORE_WS_PATH/src ] ; then
            echo "-------------------------------------------------------------------------" >&2
            echo "${bold}Status $ROS_CORE_WS_NAME:${reset}"
            vcs status "$NANOSAUR_CORE_WS_PATH/src"
        fi
        if [ -d $NANOSAUR_PERCEPTION_WS_PATH/src ] ; then
            echo "-------------------------------------------------------------------------" >&2
            echo "${bold}Status $ROS_PERC_WS_NAME:${reset}"
            vcs status "$NANOSAUR_PERCEPTION_WS_PATH/src"
        fi
    fi
    # Status Docker
    if [[ $PLATFORM = "robot" ]] ; then
        echo "-------------------------------------------------------------------------" >&2
        echo "${bold}Docker status:${reset}"
        docker-compose -f $NANOSAUR_DATA/docker-compose.yml ps -a
    fi
    echo "-------------------------------------------------------------------------" >&2
}

############################ MAIN function #####################################################

usage()
{
    if [ "$1" != "" ]; then
        echo "${red}$1${reset}" >&2
    fi

    local name=$(basename ${0})
    echo "$name is your manager to control, update your robot or your desktop to work with nanosaur." >&2
    echo "${bold}Commands:${reset}" >&2
    echo "  $name help                     This help" >&2
    echo "  $name info                     Status" >&2
    echo "  $name config                   Open/create robot.yml in ${bold}$NANOSAUR_DATA/param${reset} (use nano)" >&2
    echo "  $name domain                   Set ROS_DOMAIN_ID" >&2 # https://docs.ros.org/en/ros2_documentation/foxy/Concepts/About-Domain-ID.html
    echo "  $name install                  Install nanosaur environment." >&2
    echo "  $name update                   Update docker and scripts" >&2
    if [[ $PLATFORM = "desktop" ]] ; then
        echo "  $name build                    Build developer boards" >&2
        echo "  $name branch                   Set branch nanoasur projects" >&2
    else
        echo "  $name distro                   Set nanoasur distribution" >&2
        echo "  $name network [host/bridge]    Select network configuration" >&2
        echo "  $name wakeup/down              start/stop nanosaur systems (eq. nanosaur up -d)" >&2
        echo "  $name [start/restart/stop/up/logs/top/exec]  Control nanosaur docker" >&2
        echo "  $name clean                    clean all dangling images" >&2
    fi
    echo ""
    echo "$name managager ${bold}v$NANOSAUR_VERSION${reset} | Configuration folder is in ${bold}$NANOSAUR_DATA${reset}" >&2
}

main()
{
	# Check if run in sudo
    if [[ `id -u` -eq 0 ]] ; then 
        echo "${red}Please don't run as root${reset}" >&2
        exit 1
    fi
    local option=$1
    if [ -z "$option" ] ; then
        usage
        exit 0
    fi
    # Load all arguments except the first one
    local arguments=${@:2}

    # Options
    if [ $option = "help" ] || [ $option = "-h" ]; then
        usage
        exit 0
    elif [ $option = "info" ] ; then
        info $arguments
        exit 0
    elif [ $option = "config" ] ; then
        nano $ROBOT_FILE_PATH
        exit 0
    elif [ $option = "domain" ] ; then
        set_domain $arguments
        exit 0
    elif [ $option = "install" ] ; then
        installer $arguments
        exit 0
    elif [ $option = "update" ] ; then
        # Update nanosaur
        update $arguments
        exit 0
    fi

    # Specific options for desktop/robot
    if [[ $PLATFORM = "desktop" ]] ; then
        if [ $option = "build" ] ; then
            build $arguments
            exit 0
        elif [ $option = "branch" ] ; then
            set_branch $arguments
            exit 0
        fi
    else
        # Enable all docker options
        if [ $option = "distro" ] ; then
            set_distro $arguments
            exit 0
        elif [ $option = "network" ] ; then
            if [ -z "$arguments" ] ; then
                DOCKER_NETWORK="host"
            else
                DOCKER_NETWORK=$arguments
            fi
            echo "Network ${green}nanosaur${reset}: ${bold}$DOCKER_NETWORK${reset}" >&2
            # Saving parameters
            config_save
            exit 0
        elif [ $option = "up" ] || [ $option = "start" ] || [ $option = "restart" ] || 
                [ $option = "stop" ] || [ $option = "down" ] || [ $option = "logs" ] || 
                [ $option = "top" ] || [ $option = "exec" ] ; then
            # Run docker compose
            docker-compose -f $NANOSAUR_DATA/docker-compose.yml $option $arguments
            exit 0
        elif [ $option = "wakeup" ] ; then
            docker-compose -f $NANOSAUR_DATA/docker-compose.yml up -d
            exit 0
        elif [ $option = "clean" ] ; then
            echo "${green}Clean all dangling images${reset}" >&2
            # prune all images
            docker image prune $arguments
            exit 0
        elif [ $option = "run" ] ; then
            local image_name=$2
            local arguments=${@:3}
            if [ -z $image_name ] ; then
                # Get list of all services availabe
                # local services=$(docker-compose -f $NANOSAUR_DATA/docker-compose.yml ps --services)

                # echo "${yellow}Please select an image to load: ${bold}[$services]${reset}" >&2
                echo "${yellow}Load default image $${reset}" >&2
                image_name="core" 
            fi
            # Load command option
            local docker_cmd="bash"
            if [ ! -z "$arguments" ] ; then
                docker_cmd=$arguments
            fi
            echo "${green}Run a new nanosaur docker${reset}" >&2
            # Print configuration
            echo "${bold}Configuration:${reset}"
            config_info
            echo "---------------------------------" >&2
            # Check volume
            local WORKSPACE_DOCKER=""
            # Check if exist nanosaur workspace on robot folder
            local domain=""
            if [ ! -z ${ROS_DOMAIN_ID+x} ] ; then
                domain="-e ROS_DOMAIN_ID=$ROS_DOMAIN_ID"
            fi
            # Start docker image
            if [ $image_name = "core" ] ; then
                if [ -d $NANOSAUR_CORE_WS_PATH ] ; then
                    echo " - ${bold}Load volume:${reset} ${yellow}$NANOSAUR_CORE_WS_PATH${reset}" >&2
                    WORKSPACE_DOCKER="-v $NANOSAUR_CORE_WS_PATH/src:/opt/ros_ws/src/"
                fi
                # Run docker
                docker run -it --rm --network host \
                            --device /dev/i2c-0 \
                            --device /dev/i2c-1 \
                            --device /dev/input \
                            -v /run/jtop.sock:/run/jtop.sock \
                            -v /run/ros2sm.sock:/run/ros2sm.sock \
                            $domain \
                            $WORKSPACE_DOCKER \
                            nanosaur/nanosaur:$DOCKER_TAG $docker_cmd
            elif [ $image_name = "perception" ] ; then
                # Load perception workspace
                if [ -d $NANOSAUR_PERCEPTION_WS_PATH ] ; then
                    echo " - ${bold}Load volume:${reset} ${yellow}$NANOSAUR_PERCEPTION_WS_PATH${reset}" >&2
                    WORKSPACE_DOCKER="-v $NANOSAUR_PERCEPTION_WS_PATH/src:/opt/ros_ws/src/"
                fi
                # Load isaac ros workspace
                local ISAAC_WS_DOCKER=""
                if [ -d $ISAAC_ROS_WS_PATH ] ; then
                    echo " - ${bold}Load volume:${reset} ${yellow}$ISAAC_ROS_WS_PATH${reset}" >&2
                    ISAAC_WS_DOCKER="-v $ISAAC_ROS_WS_PATH/src:/opt/isaac_ros_ws/src/"
                fi
                # Run docker
                docker run --runtime nvidia -it --rm --network host --privileged \
                            -v /tmp/argus_socket:/tmp/argus_socket \
                            $domain \
                            $WORKSPACE_DOCKER \
                            $ISAAC_WS_DOCKER \
                            nanosaur/perception:$DOCKER_TAG $docker_cmd
            else
                echo "${yellow}Load default docker image ${bold}$N1${reset}" >&2
                docker run -it --rm --network host $domain \
                            nanosaur/nanosaur:$DOCKER_TAG $docker_cmd
            fi
            # Exit option run
            exit 0
        fi
    fi

    usage "[ERROR] Unknown option: $option" >&2
    exit 1
}


# Detect if is sourced or not
# https://stackoverflow.com/questions/2683279/how-to-detect-if-a-script-is-being-sourced
if [ "${BASH_SOURCE-}" = "$0" ] ; then
    main $@
    exit 0
fi

# Check if is running on Desktop platform
if [ $PLATFORM != "desktop" ] ; then
    echo "${red}You must source this script only from a Desktop machine${reset}" >&2
    return
fi

deactivate () {

    # https://stackoverflow.com/questions/8760505/is-it-possible-to-unsource-in-bash
    # Restore .bashrc
    if [ ! "${1-}" = "nondestructive" ] ; then
        exec bash
        # Load ROS_DOMAIN_ID
        if [ ! -z ${ROS_DOMAIN_ID+x} ] ; then
            unset ROS_DOMAIN_ID
        fi
    fi

    # The hash command must be called to get it to forget past
    # commands. Without forgetting past commands the $PATH changes
    # we made may not be respected
    hash -r 2>/dev/null

    if ! [ -z "${_OLD_VIRTUAL_PS1+_}" ] ; then
        PS1="$_OLD_VIRTUAL_PS1"
        export PS1
        unset _OLD_VIRTUAL_PS1
    fi

    unset VIRTUAL_ENV
    if [ ! "${1-}" = "nondestructive" ] ; then
    # Self destruct!
        unset -f deactivate
    fi
}

# unset irrelevant variables
deactivate nondestructive

# Check ROS2 workspace and nanosaur workspace
if [ ! -d $(dirname $ROS2_PATH) ] ; then
    echo "${red}ROS2 is not installed in $(dirname $ROS2_PATH)${reset}" >&2
    return
fi
# Load ROS2 workspace
source $ROS2_PATH
# Load ROS_DOMAIN_ID
if [ ! -z ${ROS_DOMAIN_ID+x} ] ; then
    export ROS_DOMAIN_ID=$ROS_DOMAIN_ID
fi

if [ ! -d $NANOSAUR_CORE_WS_PATH/install ] ; then
    echo "${yellow}Nanosaur workspace is missing or not builded check ${bold}$NANOSAUR_CORE_WS_PATH${reset}" >&2
else
    # Load Nanosaur workspace
    source $NANOSAUR_CORE_WS_PATH/install/setup.bash
fi

# Setup PS1
if [ -z "${VIRTUAL_ENV_DISABLE_PROMPT-}" ] ; then
    _OLD_VIRTUAL_PS1="${PS1-}"
    # Rewrite PS1
    PS1="${bold}($ROBOT_NAME)${reset} ${PS1-}"
    if [ ! -z ${ROS_DOMAIN_ID+x} ] ; then
        if [ $ROS_DOMAIN_ID -ne 0 ]; then
            PS1="${bold}${blue}id=$ROS_DOMAIN_ID${reset} ${PS1-}"
        fi
    fi
    export PS1
fi

# The hash command must be called to get it to forget past
# commands. Without forgetting past commands the $PATH changes
# we made may not be respected
hash -r 2>/dev/null
# EOF
