<?xml version="1.0"?>
<robot name="omniwheel"
    xmlns:xacro="http://ros.org/wiki/xacro">


    <xacro:macro name="omniwheel" params="parent type position xyz">

        <!-- Define orientation -->
        <xacro:if value="${type == 'left'}">
            <xacro:property name="orientation" value="-1"/>
        </xacro:if>
        <xacro:if value="${type == 'right'}">
            <xacro:property name="orientation" value="1"/>
        </xacro:if>
        <!-- Define orientation -->
        <xacro:if value="${position == 'front'}">
            <xacro:property name="motor_orientation" value="1"/>
            <xacro:property name="fdir1_direction" value="-1"/>
        </xacro:if>
        <xacro:if value="${position == 'rear'}">
            <xacro:property name="motor_orientation" value="0"/>
            <xacro:property name="fdir1_direction" value="1"/>
        </xacro:if>
        <!--radius definition-->
        <xacro:property name="omni_wheel_mass" value="0.015"/>
        <xacro:property name="omni_wheel_radius" value="${0.037 / 2}"/>
        <xacro:property name="omni_wheel_height" value="0.0226"/>

        <xacro:macro name="inertial_cylinder" params="m r h">
        <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
                    iyy="${m*r*r/2}" iyz = "0"
                    izz="${m*(3*r*r+h*h)/12}" />
        </xacro:macro>

        <xacro:macro name="inertial_sphere" params="m r">
        <inertia ixx="${(2/5) * m * (r*r)}" ixy="0.0" ixz="0.0"
                    iyy="${(2/5) * m * (r*r)}" iyz="0.0"
                izz="${(2/5) * m * (r*r)}" />
        </xacro:macro>  

        <joint name="motor_${type}_${position}_joint" type="fixed">
            <origin xyz="${xyz}" rpy="${orientation * M_PI/2} 0 0" />
            <parent link="${parent}"/>
            <child link="motor_${type}_${position}"/>
        </joint>

        <link name="motor_${type}_${position}">
            <visual>
                <origin xyz="0 0 -0.024" rpy="0 0 ${motor_orientation * M_PI}" />
                <geometry>
                    <mesh filename="${path_meshes}/parts/motor_block.stl"/>
                </geometry>
                <material name="Gold" />
            </visual>
        </link>

        <joint name="omniwheel_${type}_${position}_joint" type="continuous">
            <origin xyz="0 0 ${omni_wheel_height / 2}" rpy="0 0 0" />
            <parent link="motor_${type}_${position}"/>
            <child link="omniwheel_${type}_${position}"/>
            <axis xyz="0 0 1" />
            <limit effort="1000" velocity="1000"/>
        </joint>

        <link name="omniwheel_${type}_${position}">
            <visual>
                <origin xyz="0 0 -${omni_wheel_radius / 2}" rpy="0 0 0" />
                <geometry>
                    <mesh filename="${path_meshes}/parts/mecanum_cover.stl"/>
                </geometry>
                <material name="Black" />
            </visual>
            <!-- Collision cylinder -->
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <!--<sphere radius="${omni_wheel_radius}" />-->
                    <cylinder length="${omni_wheel_height}" radius="${omni_wheel_radius}"/>
                </geometry>
                <material name="Black" />
            </collision>
            <!-- Inertia -->
            <inertial>
                <mass value="${omni_wheel_mass}"/>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <!--<xacro:inertial_sphere  m="${omni_wheel_mass}" r="${omni_wheel_radius}" />-->
                <xacro:inertial_cylinder  m="${omni_wheel_mass}" r="${omni_wheel_radius}" h="${omni_wheel_height}" />
            </inertial>
        </link>

        <joint name="omniwheel_${type}_${position}_wheels_joint" type="fixed">
            <origin xyz="0 0 0" rpy="0 0 0" />
            <parent link="omniwheel_${type}_${position}"/>
            <child link="omniwheel_${type}_${position}_wheels"/>
            <axis xyz="0 0 1" />
        </joint>

        <link name="omniwheel_${type}_${position}_wheels">
            <visual>
                <origin xyz="0 0 -${omni_wheel_radius / 2}" rpy="0 0 0" />
                <geometry>
                    <mesh filename="${path_meshes}/parts/mecanum_wheels.stl"/>
                </geometry>
                <material name="Green" />
            </visual>
        </link>

        <!-- Reference https://github.com/gazebosim/gz-sim/issues/2261 -->
        <gazebo reference="omniwheel_${type}_${position}">
            <mu1 value="0.01"/>
            <mu2 value="0.01"/>
        </gazebo>


    </xacro:macro>

</robot>