<?xml version="1.0"?>
<robot name="robot" xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- utilities -->
    <xacro:include filename="$(find nanosaur_description)/urdf/utilities.urdf.xacro" />
    <!-- nanosaur parts -->
    <xacro:include filename="$(find nanosaur_description)/urdf/properties.urdf.xacro" />
    <xacro:include filename="$(find nanosaur_description)/urdf/base.urdf.xacro" />
    <xacro:include filename="$(find nanosaur_description)/urdf/mecanum.urdf.xacro" />
    <xacro:include filename="$(find nanosaur_description)/urdf/flap/flap.urdf.xacro" />
    <xacro:include filename="$(find nanosaur_description)/urdf/flap/flap_LD06.urdf.xacro" />
    <xacro:include filename="$(find nanosaur_description)/urdf/head/head.urdf.xacro" />
    <xacro:include filename="$(find nanosaur_description)/urdf/head/head_realsense.urdf.xacro" />

    <xacro:macro name="nanosaur" params="camera_type lidar_type rollers use_nominal_extrinsics path_meshes:=package://nanosaur_description/meshes">

        <link name="base_link"/>

        <joint name="chassis_to_base" type="fixed">
            <parent link="base_link"/>
            <child link="nanosaur_base"/>
            <origin xyz="0 0 ${mecanum_radius}" rpy="0 0 0"/>
        </joint>

        <xacro:nanosaur_base 
                base_name="nanosaur_base"
                length="${nanosaur_length}"
                width="${nanosaur_width}"
                height="${nanosaur_height}"
                mass="${nanosaur_mass}" />

        <xacro:mecanum_wheel
                name="front_left"
                side="1"
                parent="nanosaur_base"
                enable_rollers="${rollers}"
                radius="${mecanum_radius}"
                length="${mecanum_length}"
                mass="${mecanum_mass}"
                radius_roller="${mecanum_radius_roller}"
                length_roller="${mecanum_length_roller}"
                mass_roller="${mecanum_mass_roller}"
                mu="${mecanum_friction}">
                <origin xyz="${nanosaur_wheelbase / 2} ${nanosaur_wheel_separation / 2} 0" rpy="0 0 ${M_PI/2}"/>
        </xacro:mecanum_wheel>

        <xacro:mecanum_wheel
                name="front_right"
                side="-1"
                parent="nanosaur_base"
                enable_rollers="${rollers}"
                radius="${mecanum_radius}"
                length="${mecanum_length}"
                mass="${mecanum_mass}"
                radius_roller="${mecanum_radius_roller}"
                length_roller="${mecanum_length_roller}"
                mass_roller="${mecanum_mass_roller}"
                mu="${mecanum_friction}">
                <origin xyz="${nanosaur_wheelbase / 2} ${-nanosaur_wheel_separation / 2} 0" rpy="0 0 ${M_PI/2}"/>
        </xacro:mecanum_wheel>

        <xacro:mecanum_wheel
                name="rear_left"
                side="1"
                parent="nanosaur_base"
                enable_rollers="${rollers}"
                radius="${mecanum_radius}"
                length="${mecanum_length}"
                mass="${mecanum_mass}"
                radius_roller="${mecanum_radius_roller}"
                length_roller="${mecanum_length_roller}"
                mass_roller="${mecanum_mass_roller}"
                mu="${mecanum_friction}">
                <origin xyz="${-nanosaur_wheelbase / 2} ${nanosaur_wheel_separation / 2} 0" rpy="0 0 ${M_PI/2}"/>
        </xacro:mecanum_wheel>

        <xacro:mecanum_wheel
                name="rear_right"
                side="-1"
                parent="nanosaur_base"
                enable_rollers="${rollers}"
                radius="${mecanum_radius}"
                length="${mecanum_length}"
                mass="${mecanum_mass}"
                radius_roller="${mecanum_radius_roller}"
                length_roller="${mecanum_length_roller}"
                mass_roller="${mecanum_mass_roller}"
                mu="${mecanum_friction}">
                <origin xyz="${-nanosaur_wheelbase / 2} ${-nanosaur_wheel_separation / 2} 0" rpy="0 0 ${M_PI/2}"/>
        </xacro:mecanum_wheel>

        <!-- Nanosaur heads -->
        <xacro:if value="${camera_type == 'empty'}">
            <xacro:nanosaur_head parent="nanosaur_chassis" />
        </xacro:if>
        <xacro:if value="${camera_type == 'realsense'}">
            <xacro:nanosaur_head_realsense parent="nanosaur_chassis" name="camera" use_nominal_extrinsics="${use_nominal_extrinsics}" />
        </xacro:if>

        <!-- Nanosaur flap -->
        <xacro:if value="${lidar_type == 'empty'}">
            <xacro:nanosaur_flap parent="nanosaur_chassis" />
        </xacro:if>
        <xacro:if value="${lidar_type == 'LD06'}">
            <xacro:nanosaur_flap_LD06 parent="nanosaur_chassis" />
        </xacro:if>

    </xacro:macro>

</robot>