<?xml version="1.0"?>
<robot name="robot" xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- utilities -->
    <xacro:include filename="$(find nanosaur_description)/urdf/utilities.urdf.xacro" />
    <!-- nanosaur parts -->
    <xacro:include filename="$(find nanosaur_description)/urdf/properties.urdf.xacro" />
    <xacro:include filename="$(find nanosaur_description)/urdf/base.urdf.xacro" />
    <xacro:include filename="$(find nanosaur_description)/urdf/mecanum.urdf.xacro" />
    <xacro:include filename="$(find nanosaur_description)/urdf/flap/flap.urdf.xacro" />
    <xacro:include filename="$(find nanosaur_description)/urdf/flap/flap_LD06.urdf.xacro" />
    <xacro:include filename="$(find nanosaur_description)/urdf/head/head.urdf.xacro" />
    <xacro:include filename="$(find nanosaur_description)/urdf/head/head_realsense.urdf.xacro" />

    <xacro:macro name="nanosaur" params="head_type flap_type use_nominal_extrinsics path_meshes:=package://nanosaur_description/meshes">

        <link name="base_link"/>

        <joint name="chassis_to_base" type="fixed">
            <parent link="base_link"/>
            <child link="nanosaur_base"/>
            <origin xyz="0 0 ${mecanum_radius}" rpy="0 0 0"/>
        </joint>

        <xacro:nanosaur_base 
                base_name="nanosaur_base"
                length="${nanosaur_length}"
                width="${nanosaur_width}"
                height="${nanosaur_height}"
                mass="${nanosaur_mass}" />

        <xacro:mecanum_wheel
                position="front"
                side="left"
                parent="nanosaur_base"
                radius="${mecanum_radius}"
                length="${mecanum_length}"
                xyz="${nanosaur_wheelbase / 2} ${nanosaur_wheel_separation / 2} 0"
                mass="${mecanum_mass}"
                mu="${mecanum_friction}" />

        <xacro:mecanum_wheel
                position="front"
                side="right"
                parent="nanosaur_base"
                radius="${mecanum_radius}"
                length="${mecanum_length}"
                xyz="${nanosaur_wheelbase / 2} -${nanosaur_wheel_separation / 2} 0"
                mass="${mecanum_mass}"
                mu="${mecanum_friction}" />

        <xacro:mecanum_wheel
                position="rear"
                side="left"
                parent="nanosaur_base"
                radius="${mecanum_radius}"
                length="${mecanum_length}"
                xyz="-${nanosaur_wheelbase / 2} ${nanosaur_wheel_separation / 2} 0"
                mass="${mecanum_mass}"
                mu="${mecanum_friction}" />

        <xacro:mecanum_wheel
                position="rear"
                side="right"
                parent="nanosaur_base"
                radius="${mecanum_radius}"
                length="${mecanum_length}"
                xyz="-${nanosaur_wheelbase / 2} -${nanosaur_wheel_separation / 2} 0"
                mass="${mecanum_mass}"
                mu="${mecanum_friction}" />   

        <!-- Nanosaur heads -->
        <xacro:if value="${head_type == 'empty'}">
            <xacro:nanosaur_head parent="nanosaur_chassis" />
        </xacro:if>
        <xacro:if value="${head_type == 'realsense'}">
            <xacro:nanosaur_head_realsense parent="nanosaur_chassis" name="camera" use_nominal_extrinsics="${use_nominal_extrinsics}" />
        </xacro:if>

        <!-- Nanosaur flap -->
        <xacro:if value="${flap_type == 'empty'}">
            <xacro:nanosaur_flap parent="nanosaur_chassis" />
        </xacro:if>
        <xacro:if value="${flap_type == 'LD06'}">
            <xacro:nanosaur_flap_LD06 parent="nanosaur_chassis" />
        </xacro:if>

    </xacro:macro>

</robot>