
services:

  # service always disabled
  isaac-sim:
    image: nanosaur/simulation:isaac-sim
    container_name: isaac-sim
    runtime: nvidia
    environment:
      - ACCEPT_EULA=Y
      - PRIVACY_CONSENT=Y
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - USER=${USER}
      - HOST_USER_UID=${USER_UID}
      - HOST_USER_GID=${USER_GID}
    network_mode: host
    ipc: host
    stdin_open: true
    tty: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROBOT_HOME}/isaac-sim-cache/cache/kit:/isaac-sim/kit/cache:rw
      - ${ROBOT_HOME}/isaac-sim-cache/cache/ov:/home/ubuntu/.cache/ov:rw
      - ${ROBOT_HOME}/isaac-sim-cache/cache/pip:/home/ubuntu/.cache/pip:rw
      - ${ROBOT_HOME}/isaac-sim-cache/cache/glcache:/home/ubuntu/.cache/nvidia/GLCache:rw
      - ${ROBOT_HOME}/isaac-sim-cache/cache/computecache:/home/ubuntu/.nv/ComputeCache:rw
      - ${ROBOT_HOME}/isaac-sim-cache/logs:/home/ubuntu/.nvidia-omniverse/logs:rw
      - ${ROBOT_HOME}/isaac-sim-cache/data:/home/ubuntu/.local/share/ov/data:rw
      - ${ROBOT_HOME}/isaac-sim-cache/documents:/home/ubuntu/Documents:rw
    profiles:
      - "isaac-sim"

  # service always disabled
  gazebo:
    image: nanosaur/simulation:gazebo
    container_name: gazebo
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - USER=${USER}
      - HOST_USER_UID=${USER_UID}
      - HOST_USER_GID=${USER_GID}
    network_mode: host
    ipc: host
    stdin_open: true
    tty: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /home/rbonghi/.Xauthority:/home/admin/.Xauthority:rw
    profiles:
      - "gazebo"

  core:
    image: nanosaur/nanosaur:${CORE_TAG}
    container_name: ${ROBOT_NAME}-${CORE_TAG}
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - USER=${USER}
      - HOST_USER_UID=${USER_UID}
      - HOST_USER_GID=${USER_GID}
    command: >
      ros2 launch nanosaur_${SIMULATION} nanosaur_bridge.launch.py ${COMMANDS}
    network_mode: host
    ipc: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /run/jtop.sock:/run/jtop.sock:ro

  perception:
    image: nanosaur/perception:${PERCEPTION_TAG}
    container_name: ${ROBOT_NAME}-perception-${CORE_TAG}
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - USER=${USER}
      - HOST_USER_UID=${USER_UID}
      - HOST_USER_GID=${USER_GID}
    command: >
      ros2 launch nanosaur_perception perception.launch.py ${COMMANDS}
    runtime: nvidia
    network_mode: host
    ipc: host
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - /run/jtop.sock:/run/jtop.sock:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/home/admin/.Xauthority:rw
