
services:

  # service always disabled
  nanosaur_gazebo:
    image: nanosaur/simulation:gazebo
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - USER=${USER}
      - HOST_USER_UID=${USER_UID}
      - HOST_USER_GID=${USER_GID}
    network_mode: host
    ipc: host
    stdin_open: true
    tty: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /home/rbonghi/.Xauthority:/home/admin/.Xauthority:rw
    profiles:
      - disabled

  nanosaur_simulator:
    image: nanosaur/nanosaur:simulation
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - USER=${USER}
      - HOST_USER_UID=${USER_UID}
      - HOST_USER_GID=${USER_GID}
    command: >
      ros2 launch nanosaur_${SIMULATION} nanosaur_bridge.launch.py ${COMMANDS}
    network_mode: host
    ipc: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /run/jtop.sock:/run/jtop.sock:ro

  nanosaur-perception:
    image: nanosaur/perception:simulation
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - USER=${USER}
      - HOST_USER_UID=${USER_UID}
      - HOST_USER_GID=${USER_GID}
    command: >
      ros2 launch nanosaur_perception perception.launch.py ${COMMANDS}
    runtime: nvidia
    network_mode: host
    ipc: host
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - /run/jtop.sock:/run/jtop.sock:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/home/admin/.Xauthority:rw